### ISSUE TITLE
goldenhopper-1.2.8-1.19.jar Crashing when placing hopper. (Forge 1.19.2)

### ISSUE THREAD

**Issue by Minebrah** [MrCrayfish/GoldenHopper#32]
https://gist.github.com/Minebrah/ea22fba7a1fa221efd274133d9535bc0

[17May2024 19:12:37.869] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[client-1.19.2-20220805.130853-srg.jar%231859!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%231859!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%231859!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%231859!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%231859!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class com.mrcrayfish.goldenhopper.world.level.block.entity.GoldenHopperBlockEntity cannot be cast to class com.performant.coremod.entity.IHopperTEAccessor (com.mrcrayfish.goldenhopper.world.level.block.entity.GoldenHopperBlockEntity is in module goldenhopper@1.2.8 of loader 'TRANSFORMER' @24caa80; com.performant.coremod.entity.IHopperTEAccessor is in module perf@5.8 of loader 'TRANSFORMER' @24caa80)
	at net.minecraft.world.level.block.entity.HopperBlockEntity.redirect$bkm000$getItems(HopperBlockEntity.java:563) ~[client-1.19.2-20220805.130853-srg.jar%231859!/:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.m_155552_(HopperBlockEntity.java:188) ~[client-1.19.2-20220805.130853-srg.jar%231859!/:?]
	at com.mrcrayfish.goldenhopper.world.level.block.entity.AbstractHopperBlockEntity.lambda$serverTick$1(AbstractHopperBlockEntity.java:177) ~[goldenhopper-1.2.8-1.19.jar%231339!/:1.2.8-1.19]
	at com.mrcrayfish.goldenhopper.world.level.block.entity.AbstractHopperBlockEntity.attemptTransferItems(AbstractHopperBlockEntity.java:191) ~[goldenhopper-1.2.8-1.19.jar%231339!/:1.2.8-1.19]
	at com.mrcrayfish.goldenhopper.world.level.block.entity.AbstractHopperBlockEntity.serverTick(AbstractHopperBlockEntity.java:177) ~[goldenhopper-1.2.8-1.19.jar%231339!/:1.2.8-1.19]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%231859!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%231859!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%231859!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%231859!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%231859!/:?]
	... 5 more
[17May2024 19:12:37.875] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: C:\Users\world\AppData\Roaming\.minecraft\crash-reports\crash-2024-05-17_19.12.37-server.txt

The crash report was blank. Never had that happen before

**Comment by Minebrah** [comment]
It looks like maybe an incompatibility with "Performant" mod. But that's just my guess.
